<?xml version="1.0" encoding="UTF-8"?><testsuite errors="0" failures="1" name="testcases.LoginTest" skipped="0" tests="1" time="20.84" timestamp="2021-09-30 05:10:38"><testcase classname="testcases.LoginTest" name="Executing Login Test"><failure message="Field should be present" type="java.lang.AssertionError">Field should be present</failure><system-err>Field should be present&#13;
testcases.LoginTest.doLogin(LoginTest.java:38)&#13;
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
</system-err></testcase></testsuite>